const data = [
  {
    id: 1,
    title: 'Under-13 Training Camp',
    imgThumbnail:
      'https://www.fcbarcelona.com/photo-resources/2020/02/12/80fa3945-f7ce-471a-8409-4c1c0c006126/20012617384119390956.jpg?width=480&height=480',
    img: 'https://www.fcbarcelona.com/photo-resources/2020/02/12/80fa3945-f7ce-471a-8409-4c1c0c006126/20012617384119390956.jpg?width=1600&height=700',
    desc: 'The Under-13 summer camp is for the children who are really passionate for football at their young age. This camp is exclusively arranged for the kids to train them in professional and fun way and make them ready for the next level. So, fill up the form and get the details on your email. Be the next Champ.',
    details:
      'Sports Academy is the flagship Sports school aimed at boys and girls between 6 and 18 years of age and its main objective is to provide a comprehensive training environment for their pupils. This method of schooling, exported to the rest of the world, attempts to extend the Sports model and promote the Club’s working philosophy internationally. The Sports Academy works via their own particular model, based on the Sports methodology which includes a creative and attacking brand of football and the promotion of positive values such as respect, effort, ambition, teamwork and humility.',
    fee: 200,
    duration: '6 months',
    methodlogyTitle: 'A Successful Methodology',
    methodology:
      'The official Sports football academy is a school of life that nurtures young people through football. Its aim is to take the clubs style of play to the world, giving any boy or girl who identifies with our values ​​and who wants to learn to play like Sports the opportunity to become a Sports player.This football education programme was developed by combining both training and competition based on Sportss methodology. This is a methodology that aims to develop autonomous and creative players who represent the Sports values (humility effort ambition respect and teamwork), are capable of organising themselves as a group to play attractive football, and are characterised by taking the initiative through possession of the ball.At the Sports Academy, players have fun playing football, practicing moves set within the specific context of the game. They also have to find solutions to these situations by using their skills, working in coordination with their teammates and subsequently being able to act efficiently and efficaciously when playing competitive football the Sports way. Players are guided by Sports coaches, who support them with decision making and ensure that the players themselves are always at the heart of their own learning process.The clubs own unique methodology is designed for sharing the Sports system with the world, exporting its style on an international scale through the Sports Academies in all five continents. Each of these Sports Academies is run by a Project Director trained at Sports who receives specialist assistance from Barcelona and whose role is to implement this successful methodology, adapting it to the particularities of each region and thereby making sure that our football becomes universal.',
  },
  {
    id: 2,
    title: 'Under-17 Training Camp',
    imgThumbnail:
      'https://www.fcbarcelona.com/photo-resources/2020/01/23/6ec2ef5a-d31d-476c-b6a0-74210218ac7e/galeria62.jpg?width=480&height=480',
    img: 'https://www.fcbarcelona.com/photo-resources/2020/01/23/6ec2ef5a-d31d-476c-b6a0-74210218ac7e/galeria62.jpg?width=1600&height=700',
    desc: 'The Under-13 summer camp is for the children who are really passionate for football at their young age. This camp is exclusively arranged for the kids to train them in professional and fun way and make them ready for the next level. So, fill up the form and get the details on your email. Be the next Champ.',
    details:
      'Sports Academy is the flagship Sports school aimed at boys and girls between 14 and 18 years of age and its main objective is to provide a comprehensive training environment for their pupils. This method of schooling, exported to the rest of the world, attempts to extend the Sports model and promote the Club’s working philosophy internationally. The Sports Academy works via their own particular model, based on the Sports methodology which includes a creative and attacking brand of football and the promotion of positive values such as respect, effort, ambition, teamwork and humility.',
    fee: 450,
    duration: '6 months',
    methodlogyTitle: 'A Successful Methodology',
    methodology:
      'The official Sports football academy is a school of life that nurtures young people through football. Its aim is to take the clubs style of play to the world, giving any boy or girl who identifies with our values ​​and who wants to learn to play like Sports the opportunity to become a Sports player.This football education programme was developed by combining both training and competition based on Sportss methodology. This is a methodology that aims to develop autonomous and creative players who represent the Sports values (humility effort ambition respect and teamwork), are capable of organising themselves as a group to play attractive football, and are characterised by taking the initiative through possession of the ball.At the Sports Academy, players have fun playing football, practicing moves set within the specific context of the game. They also have to find solutions to these situations by using their skills, working in coordination with their teammates and subsequently being able to act efficiently and efficaciously when playing competitive football the Sports way. Players are guided by Sports coaches, who support them with decision making and ensure that the players themselves are always at the heart of their own learning process.The clubs own unique methodology is designed for sharing the Sports system with the world, exporting its style on an international scale through the Sports Academies in all five continents. Each of these Sports Academies is run by a Project Director trained at Sports who receives specialist assistance from Barcelona and whose role is to implement this successful methodology, adapting it to the particularities of each region and thereby making sure that our football becomes universal.',
  },
  {
    id: 3,
    title: 'Under-19 Training Camp',
    imgThumbnail:
      'https://www.fcbarcelona.com/photo-resources/2019/12/12/f1dec3b6-7d33-4ae6-b646-cf088e5262fd/web_academy_3200x1400_residency.jpg?width=480&height=480',
    img: 'https://www.fcbarcelona.com/photo-resources/2019/12/12/f1dec3b6-7d33-4ae6-b646-cf088e5262fd/web_academy_3200x1400_residency.jpg?width=1600&height=700',
    desc: 'The Under-13 summer camp is for the children who are really passionate for football at their young age. This camp is exclusively arranged for the kids to train them in professional and fun way and make them ready for the next level. So, fill up the form and get the details on your email. Be the next Champ.',
    details:
      'Sports Academy is the flagship Sports school aimed at boys and girls between 17 and 20 years of age and its main objective is to provide a comprehensive training environment for their pupils. This method of schooling, exported to the rest of the world, attempts to extend the Sports model and promote the Club’s working philosophy internationally. The Sports Academy works via their own particular model, based on the Sports methodology which includes a creative and attacking brand of football and the promotion of positive values such as respect, effort, ambition, teamwork and humility.',
    fee: 650,
    duration: '6 months',
    methodlogyTitle: 'A Successful Methodology',
    methodology:
      'The official Sports football academy is a school of life that nurtures young people through football. Its aim is to take the clubs style of play to the world, giving any boy or girl who identifies with our values ​​and who wants to learn to play like Sports the opportunity to become a Sports player.This football education programme was developed by combining both training and competition based on Sportss methodology. This is a methodology that aims to develop autonomous and creative players who represent the Sports values (humility effort ambition respect and teamwork), are capable of organising themselves as a group to play attractive football, and are characterised by taking the initiative through possession of the ball.At the Sports Academy, players have fun playing football, practicing moves set within the specific context of the game. They also have to find solutions to these situations by using their skills, working in coordination with their teammates and subsequently being able to act efficiently and efficaciously when playing competitive football the Sports way. Players are guided by Sports coaches, who support them with decision making and ensure that the players themselves are always at the heart of their own learning process.The clubs own unique methodology is designed for sharing the Sports system with the world, exporting its style on an international scale through the Sports Academies in all five continents. Each of these Sports Academies is run by a Project Director trained at Sports who receives specialist assistance from Barcelona and whose role is to implement this successful methodology, adapting it to the particularities of each region and thereby making sure that our football becomes universal.',
  },
  {
    id: 4,
    title: 'Development Program',
    imgThumbnail:
      'https://www.fcbarcelona.com/photo-resources/2019/05/29/9e462ef6-e631-4fc5-806d-6bd9fd96f8fc/AC4_0168.jpg?width=480&height=480',
    img: 'https://www.fcbarcelona.com/photo-resources/2019/05/29/9e462ef6-e631-4fc5-806d-6bd9fd96f8fc/AC4_0168.jpg?width=840&height=368',
    desc: 'OBJECTIVE: optimisation of the coordinative structure in the context of real game situations and based on the tactical targets that we set at Sports School The BaARÇA Escola Development Program works with small groups of a maximum of 12 players and 6 goalkeepers, and the interaction between the player and the coach is sought.',
    details:
      'Sports Academy is the flagship Sports school aimed at boys and girls between 17 and 20 years of age and its main objective is to provide a comprehensive training environment for their pupils. This method of schooling, exported to the rest of the world, attempts to extend the Sports model and promote the Club’s working philosophy internationally. The Sports Academy works via their own particular model, based on the Sports methodology which includes a creative and attacking brand of football and the promotion of positive values such as respect, effort, ambition, teamwork and humility.',
    fee: 150,
    duration: '6 months',
    methodlogyTitle: 'A Successful Methodology',
    methodology:
      'The official Sports football academy is a school of life that nurtures young people through football. Its aim is to take the clubs style of play to the world, giving any boy or girl who identifies with our values ​​and who wants to learn to play like Sports the opportunity to become a Sports player.This football education programme was developed by combining both training and competition based on Sportss methodology. This is a methodology that aims to develop autonomous and creative players who represent the Sports values (humility effort ambition respect and teamwork), are capable of organising themselves as a group to play attractive football, and are characterised by taking the initiative through possession of the ball.At the Sports Academy, players have fun playing football, practicing moves set within the specific context of the game. They also have to find solutions to these situations by using their skills, working in coordination with their teammates and subsequently being able to act efficiently and efficaciously when playing competitive football the Sports way. Players are guided by Sports coaches, who support them with decision making and ensure that the players themselves are always at the heart of their own learning process.The clubs own unique methodology is designed for sharing the Sports system with the world, exporting its style on an international scale through the Sports Academies in all five continents. Each of these Sports Academies is run by a Project Director trained at Sports who receives specialist assistance from Barcelona and whose role is to implement this successful methodology, adapting it to the particularities of each region and thereby making sure that our football becomes universal.',
  },
  {
    id: 5,
    title: 'Indoor Football',
    imgThumbnail:
      'https://www.fcbarcelona.com/photo-resources/2019/12/05/45a477c4-9ee1-4484-b3a2-8e3c663216f4/futsal3.jfif?width=480&height=480',
    img: 'https://www.fcbarcelona.com/photo-resources/2019/12/05/45a477c4-9ee1-4484-b3a2-8e3c663216f4/futsal3.jfif?width=840&height=368',
    desc: 'The main purpose of Sports Escola Futsal Barcelona is the comprehensive training of its pupils in accordance with the same model used at FC Barcelona’s own futsal academy.Sports Escola Futsal Barcelona is a futsal school for boys and girls aged between 6 and 12 years. We teach the players the basics of futsal so that they are fully prepared for the sporting challenges they’ll face in the future while also respecting the values that are so representative of FC Barcelona: humility, effort, ambition, respect and teamwork.',
    details:
      'Sports Academy is the flagship Sports school aimed at boys and girls between 17 and 20 years of age and its main objective is to provide a comprehensive training environment for their pupils. This method of schooling, exported to the rest of the world, attempts to extend the Sports model and promote the Club’s working philosophy internationally. The Sports Academy works via their own particular model, based on the Sports methodology which includes a creative and attacking brand of football and the promotion of positive values such as respect, effort, ambition, teamwork and humility.',
    fee: 350,
    duration: '4 months',
    methodlogyTitle: 'A Successful Methodology',
    methodology:
      'The official Sports football academy is a school of life that nurtures young people through football. Its aim is to take the clubs style of play to the world, giving any boy or girl who identifies with our values ​​and who wants to learn to play like Sports the opportunity to become a Sports player.This football education programme was developed by combining both training and competition based on Sportss methodology. This is a methodology that aims to develop autonomous and creative players who represent the Sports values (humility effort ambition respect and teamwork), are capable of organising themselves as a group to play attractive football, and are characterised by taking the initiative through possession of the ball.At the Sports Academy, players have fun playing football, practicing moves set within the specific context of the game. They also have to find solutions to these situations by using their skills, working in coordination with their teammates and subsequently being able to act efficiently and efficaciously when playing competitive football the Sports way. Players are guided by Sports coaches, who support them with decision making and ensure that the players themselves are always at the heart of their own learning process.The clubs own unique methodology is designed for sharing the Sports system with the world, exporting its style on an international scale through the Sports Academies in all five continents. Each of these Sports Academies is run by a Project Director trained at Sports who receives specialist assistance from Barcelona and whose role is to implement this successful methodology, adapting it to the particularities of each region and thereby making sure that our football becomes universal.',
  },
  {
    id: 6,
    title: 'Basketball',
    imgThumbnail:
      'https://www.fcbarcelona.com/photo-resources/2019/12/05/2387bd00-4706-4a95-9386-7e0537192503/basket2.jfif?width=480&height=480',
    img: 'https://www.fcbarcelona.com/photo-resources/2019/12/05/2387bd00-4706-4a95-9386-7e0537192503/basket2.jfif?width=840&height=368',
    desc: 'Sports school Basketball is a training school run by FC Barcelona aimed at children between the ages of 4 and 12. The students aged between 6 and 12 train twice a week with the younger ones having just one weekly session. Aside from the internal league matches played on every other Saturday at the Ciutat Esportiva, the students also have the chance to play in various friendly matches and tournaments that are organised during the course.',
    details:
      'Sports Academy is the flagship Sports school aimed at boys and girls between 17 and 20 years of age and its main objective is to provide a comprehensive training environment for their pupils. This method of schooling, exported to the rest of the world, attempts to extend the Sports model and promote the Club’s working philosophy internationally. The Sports Academy works via their own particular model, based on the Sports methodology which includes a creative and attacking brand of football and the promotion of positive values such as respect, effort, ambition, teamwork and humility.',
    fee: 350,
    duration: '4 months',
    methodlogyTitle: 'A Successful Methodology',
    methodology:
      'The official Sports football academy is a school of life that nurtures young people through football. Its aim is to take the clubs style of play to the world, giving any boy or girl who identifies with our values ​​and who wants to learn to play like Sports the opportunity to become a Sports player.This football education programme was developed by combining both training and competition based on Sportss methodology. This is a methodology that aims to develop autonomous and creative players who represent the Sports values (humility effort ambition respect and teamwork), are capable of organising themselves as a group to play attractive football, and are characterised by taking the initiative through possession of the ball.At the Sports Academy, players have fun playing football, practicing moves set within the specific context of the game. They also have to find solutions to these situations by using their skills, working in coordination with their teammates and subsequently being able to act efficiently and efficaciously when playing competitive football the Sports way. Players are guided by Sports coaches, who support them with decision making and ensure that the players themselves are always at the heart of their own learning process.The clubs own unique methodology is designed for sharing the Sports system with the world, exporting its style on an international scale through the Sports Academies in all five continents. Each of these Sports Academies is run by a Project Director trained at Sports who receives specialist assistance from Barcelona and whose role is to implement this successful methodology, adapting it to the particularities of each region and thereby making sure that our football becomes universal.',
  },
];
